name: Feature Request
description: Suggest a new feature or improvement to the Gambit website.
labels: ["enhancement", "website"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: request-details
    attributes:
      description: Please provide details about the feature or improvement you would like to see.
      placeholder: Describe the feature or improvement in detail.
      value: "A feature or improvement suggestion!"
    validations:
      required: true